# =========================== Basic Settings ===========================

model: models.graphs.mobilenetv1like:MobileNetV1Like

# data
data: data.cifar10:CIFAR10
batch_size: 128
test_batch_size: 128
workers: 8

# lr
lr: 0.1
lr_scheduler: cosine

# optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nestorov: False

# info
output_size: 10
image_size: 32
num_epochs: 160
in_channels: 3
topk: [1,5]

# other
resume: ''
seed: 1996
save_dir: './checkpoints'
log_dir: './runs'
evaluate: False


# =========================== Override ===========================
val_resize: 32
prune_rate: 0.775

skip_profiling: True

graph: fine_tune
setting: static

# path to the trained complete graph. e.g.
use_graph: './saved/complete_final.pt'
# path to the initialization to use. e.g.
use_init: './saved/complete_init.pt'

